- hosts: aws-k8s-master
  become: yes
  gather_facts: no      
  tasks:

    - name: "Create token command for worker nodes"
      shell: "kubeadm token create  --print-join-command"
      register: join_cmd
      args:
        warn: false

- hosts: azure-k8s-nodes
  become: yes
  tasks:

    - name: "Add Kubernetes apt-key"
      apt_key:
        url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
        state: "present"

    - name: "Add Kubernetes apt repo"
      apt_repository:
        repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
        state: "present"
        filename: "kubernetes"

    - name: "Install APT Transport HTTPS"
      apt:
        name: "apt-transport-https"
        state: "present"
        update_cache: true
    
    - name: "Docker Installation"
      apt:
        name: "docker.io"
        state: "present"
    
    - name: "Copy docker daemon file"
      copy:
        src: "../daemon.json"
        dest: "/etc/docker/"

    - name: "Restart docker service"
      service:
        name: "docker"
        state: "restarted"
    
    - name: "Install kubelet"
      apt:
        name: "kubelet"
        state: "present"

    - name: "Install kubeadm"
      apt:
        name: "kubeadm"
        state: "present"

    - name: "Join with master"
      shell: "{{ hostvars[groups['aws-k8s-master'][0]]['join_cmd']['stdout'] }}"
      ignore_errors: yes

    - name: "Create terraform env file"
      file:
        path: "/etc/profile.d/terraform.sh"
        state: "touch"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: "Add IS_CONFIGURED env var"
      lineinfile:
        path: "/etc/profile.d/terraform.sh"
        insertafter: 'EOF'
        line: "export IS_CONFIGURED=1"