- name: "Wait till nodes are reachable"
  hosts: aws-k8s-nodes
  gather_facts: no
  tasks:
    - name: "Wait for system to become reachable"
      wait_for_connection:

- hosts: aws-k8s-nodes
  tasks:

    - name: "Get the env var"
      shell: "echo $IS_CONFIGURED"
      register: configured

- name: "Include require-config play"
  import_playbook: "require-config.yaml"
  when: configured.stdout | default(0) != '1'